services:
  minio:
    image: minio/minio
    env_file:
      - .env
    container_name: django_test_minio_object_server
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web console
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 3s
      timeout: 2s
      retries: 30

  minio-mc:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - .env
    container_name: django_test_minio_mc
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO TCP port...';
      until (echo > /dev/tcp/minio/9000) >/dev/null 2>&1; do
        sleep 1;
      done;

      echo 'MinIO port is open. Setting alias...';
      until mc alias set local http://minio:9000 \"$MINIO_ACCESS_KEY\" \"$MINIO_SECRET_KEY\"; do
        sleep 1;
      done;

      echo 'Ensuring bucket exists...';

      mc mb -p local/$MINIO_STATIC_BUCKET_NAME || true;
      echo 'Setting anonymous download policy...';
      mc anonymous set download local/$MINIO_STATIC_BUCKET_NAME || true;

      mc mb -p local/$MINIO_MEDIA_BUCKET_NAME || true;
      echo 'Setting anonymous download policy for pubmedia...';
      mc anonymous set download local/$MINIO_MEDIA_BUCKET_NAME || true;

      echo 'MinIO init complete.';
      "
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}

  db:
    image: postgres:16
    env_file:
      - .env
    container_name: django_test_pg_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # Change to "5433:5432" if you have a local Postgres instance running on 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  memcached:
    image: memcached:1.6-alpine
    container_name: django_test_memcached
    command: ["memcached", "-m", "128", "-p", "11211", "-vv"]
    ports:
      - "11211:11211"

  # redis:
  #   image: redis:7-alpine
  #   container_name: django_test_redis
  #   ports:
  #     - "127.0.0.1:6379:6379"
  #   depends_on:
  #     - web
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

  web:
    build: .
    container_name: django_test_web_app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers ${WORKERS} --threads ${THREADS} --timeout ${TIMEOUT}  --access-logfile - --error-logfile - --log-level info # Adjust workers, threads, and timeout as needed for development
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE} # Specify the settings module for development ('config.settings.prod' for production)
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db

volumes:
  postgres_data:
  minio_data:
  # redis_data:
